version: '3.2'

services:
  web:
    build: web
    image: dgageot/wall-e-web
    volumes: ["./web/static:/usr/share/nginx/html"]
    ports: ["443:443"]
    secrets:
     - cert
     - key

  proxies:
    build: .
    image: dgageot/wall-e
    env_file: ${HOME}/secrets/jenkins.env
    secrets:
     - jenkins_token
     - github_token
    deploy:
      restart_policy:
        condition: on-failure

secrets:
  cert:
    file: ${HOME}/secrets/cert
  key:
    file: ${HOME}/secrets/key
  jenkins_token:
    file: ${HOME}/secrets/jenkins.token
  github_token:
    file: ${HOME}/secrets/github.wall-e.token
